app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main import assurance
urlpatterns = [
    url(r'', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^assurance_create/$', assurance.create, name='assurance_create'),
]

main/urls.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from . import views, batiment, proprietaire, suivis, contratlocation, financement, locataire, contratgestion, \
    frais, honoraire, personne, essai_pdf, assurance, pays, fonction, societe, document,\
    lettre
from main import alertes
from main.pdf import image
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.conf import settings


urlpatterns = [
    url(r'^$', views.home, name='home'),
    # login / logout urls
    url(r'^login/$', login, {'template_name': settings.LOGOUT_REDIRECT_URL}, name='login'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    # listes
    url(r'^listeComplete', views.listeComplete),
    url(r'^listeBatiments', views.listeBatiments, name='listeBatiments'),

    url(r'^listeProprietaires', proprietaire.liste_proprietaires, name='listeProprietaires'),
    url(r'^listeContratGestion/$', views.ContratGestionList.as_view(), name='contrat_gestion_list'),
    url(r'^contratGestion/(?P<pk>[0-9]+)/$', views.ContratGestionDetail.as_view(), name='contrat_gestion_detail'),
    # ecran de detail
    url(r'^batiment/([0-9]+)/$', batiment.batiment_form, name='batiment'),
    url(r'^proprietaire/(?P<proprietaire_id>[0-9]+)/$', proprietaire.proprietaire, name='proprietaire'),
    url(r'^proprietaire/update/([0-9]+)/$', proprietaire.update_proprietaire, name='update_proprietaire'),
    url(r'^proprietaire/delete/([0-9]+)/$', proprietaire.delete_proprietaire, name='delete_proprietaire'),
    url(r'^proprietaire/dadd/([0-9]+)/$', proprietaire.add_proprietaire, name='add_proprietaire'),
    url(r'^proprietaire/$', proprietaire.proprietaire_update_save, name='proprietaire-update-save'),
    url(r'^proprietaire/createb/([0-9]+)/$', proprietaire.proprietaire_create_for_batiment,
        name='proprietaire-create-batiment'),

    # old
    # url(r'^suivis/$', suivis.suivis, name='suivis'),
    # url(r'^suivis/refresh/$', suivis.refresh_suivis, name='refresh_suivis'),
    url(r'^suivis/$', suivis.suivis, name='suivis'),
    url(r'^suivis/search$', suivis.suivis_search, name='suivis_search'),
    url(r'^suivis/update$', suivis.suivis_update, name='suivis-update'),
    # url(r'^suivis/updatel/([0-9]+)/$', suivis.suivis_updatel, name='suivis-updatel'),
    url(r'^suivis/updatel/([0-9]+)/liste/$', suivis.suivis_update_liste, name='suivis-update-liste'),
    url(r'^suivis/updatel/([0-9]+)/home/$', suivis.suivis_update_home, name='suivis-update-home'),
    url(r'^suivis/updatel/([0-9]+)/location/$', suivis.suivis_update_location, name='suivis-update-location'),

    url(r'^suivis/update_suivi$', suivis.update_suivi, name='update_suivi'),


    # url(r'^update_personne/$', views.update_personne, name='update_personne'),
    url(r'^update_batiment(?:/(?P<batiment_id>[0-9]+))?/$', batiment.update, name='update_batiment'),


    # url(r'^photos/(?P<path>.*)$', 'django.views.static.serve', {
    #         'document_root': settings.MEDIA_ROOT,
    #     }),

    url(r'^fraismaintenances/$', frais.list, name='fraismaintenance_list'),
    url(r'^fraismaintenance/new/$', frais.new, name='fraismaintenance-new'),
    url(r'^fraismaintenance/create/([0-9]+)/$', frais.create, name='fraismaintenance-create'),
    url(r'^fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update, name='fraismaintenance-prepare-update'),
    url(r'^fraismaintenance/update/$', frais.update, name='fraismaintenance-update'),
    url(r'^fraismaintenance/delete/([0-9]+)/$', frais.delete_frais, name='fraismaintenance-delete'),
    url(r'^fraismaintenance/(?P<pk>[0-9]+)/$', views.FraisMaintenanceDetail.as_view(), name='fraismaintenance_detail'),

    url(r'^personne/create/$', personne.create, name='personne-create'),
    url(r'^personne/create/locataire/$', locataire.personne_create, name='personne-create-locataire'),
    url(r'^personne/create2019/$', personne.personne_create_2019, name='personne-create-2019'),
    url(r'^personne/create/proprietaire/$', proprietaire.personne_create, name='personne-create-proprietaire'),

    url(r'^personne/edit/([0-9]+)/$', personne.edit, name='personne-edit'),
    url(r'^personne/update/$', personne.update, name='personne-update'),
    url(r'^personne/delete/(?P<pk>[0-9]+)/$', views.PersonneDelete.as_view(), name='personne-delete'),
    url(r'^personne/delete2/([0-9]+)/$', views.personne_delete, name='personne-delete-2'),
    url(r'^personnes/$', personne.list, name='personne_list'),
    url(r'^personnes/search/$', personne.search, name='personne_search'),
    url(r'^validate_personne/$', personne.validate_personne, name='validate_personne'),

    url(r'^batiment/create/$', batiment.create, name='batiment-create'),
    url(r'^batiment/([0-9]+)/$', batiment.batiment_form, name='batiment'),
    url(r'^batiment/update/([0-9]+)/$', batiment.update, name='batiment-update'),
    url(r'^batiment/delete/([0-9]+)/$', batiment.delete, name='batiment-delete'),
    url(r'^batiments/$', views.BatimentList.as_view(), name='batiment_list'),
    url(r'^batiment/deletep/([0-9]+)/$', proprietaire.delete_proprietaire_batiment,
        name='delete_proprietaire_batiment'),
    url(r'^batiment/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_batiment,
        name='fraismaintenance-edit-from-batiment'),
    url(r'^location/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_location,
        name='fraismaintenance-edit-from-location'),
    url(r'^dashboard/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_dashboard,
        name='fraismaintenance-edit-from-dashboard'),
    url(r'^frais/list/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_list,
        name='fraismaintenance-edit-from-list'),

    url(r'^batiment/fraismaintenance/delete/([0-9]+)/$', frais.delete_frais_from_batiment,
        name='fraismaintenance-delete-from-batiment'),
    url(r'^location/fraismaintenance/delete/([0-9]+)/$', frais.delete_frais_from_location,
        name='fraismaintenance-delete-from-location'),
    url(r'^frais/liste/fraismaintenance/delete/([0-9]+)/$', frais.delete_frais_from_list,
        name='fraismaintenance-delete-from-list'),
    # url(r'^proprietaire/create/$', views.ProprietaireCreate.as_view(), name='proprietaire-create'),
    # url(r'^proprietaire/createb/(?P<pk>[0-9]+)/$', views.ProprietaireCreateForBatiment.as_view(),
    # name='proprietaire-create-batiment'),
    # url(r'^proprietaire/update/(?P<pk>[0-9]+)/$', views.ProprietaireUpdate.as_view(), name='proprietaire-update'),
    # url(r'^proprietaire/delete/(?P<pk>[0-9]+)/$', views.ProprietaireDelete.as_view(), name='proprietaire-delete'),
    # url(r'^proprietaires/$', views.ProprietaireList.as_view(), name='proprietaire_list'),
    # url(r'^proprietaire/(?P<pk>[0-9]+)/$', views.ProprietaireDetail.as_view(), name='proprietaire_detail'),
    url(r'^contratgestion/new/$', contratgestion.new, name='contratgestion-new'),
    url(r'^contratgestion/create/([0-9]+)/$', contratgestion.create, name='contratgestion-create'),
    # url(r'^contratgestion/update/(?P<pk>[0-9]+)/$', views.ContratGestionUpdate.as_view(),
    # name='contratgestion-update'),
    url(r'^contratgestion/delete/([0-9]+)/$', contratgestion.delete, name='contratgestion-delete'),
    url(r'^gestion/prepare/update/all/([0-9]+)/$', contratgestion.prepare_update, name='gestion-prepare-update-all'),
    url(r'^gestion/update/all/$', contratgestion.update, name='update-gestion-all'),
    url(r'^contratgestion/form/(?P<id_contrat>[0-9]+)/$', contratgestion.saveupdate, name='gestion-create-update'),



    url(r'^contratgestions/$', contratgestion.list, name='contratgestion_list'),

    # url(r'^contratgestion/(?P<pk>[0-9]+)/$', views.ContratGestionDetail.as_view(), name='contratgestion'),

    url(r'^societe/delete/(?P<pk>[0-9]+)/$', views.SocieteDelete.as_view(), name='societe-delete'),
    url(r'^societes/$', societe.list, name='societe-list'),
    url(r'^societe/(?P<pk>[0-9]+)/$', views.SocieteDetail.as_view(), name='societe'),
    url(r'^societe/create/personne/$', societe.create, name='personne-create-societe'),
    # url(r'^batiment5/(?P<pk>\d+)/$', BatimentDetailView.as_view(), batiment_info)
    url(r'^alertes/$', alertes.list, name='alerte-list'),
    url(r'^alertes/update/$', alertes.update_a_verifier, name='alerte-update-a-verifier'),
    url(r'^alertes/search/$', alertes.search, name='alerte-search'),

    # url(r'^location/create/$', views.ContratLocationCreate.as_view(), name='location-create'),
    # url(r'^location/update/(?P<pk>[0-9]+)/$', views.ContratLocationUpdate.as_view(), name='location-update'),

    url(r'^location/prepare/update/all/([0-9]+)/$', contratlocation.prepare_update, name='location-prepare-update-all'),
    url(r'^location/update/all/$', contratlocation.update, name='update-location-all'),
    url(r'^location/createb/([0-9]+)/$', contratlocation.contrat_location_for_batiment,

main/models/alerte.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.db import models
from django.contrib import admin
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from main.models.enums import alerte_etat


class AlerteAdmin(admin.ModelAdmin):
    list_filter = ('etat',)


class Alerte(models.Model):

    description = models.TextField(verbose_name=u"Description")
    date_alerte = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True,
                                   verbose_name=u"Date alerte")
    contrat_gestion = models.ForeignKey('ContratGestion', blank=True, null=True, verbose_name=u"Contrat de gestion")
    contrat_location = models.ForeignKey('ContratLocation', blank=True, null=True, verbose_name=u"Contrat location")
    etat = models.CharField(max_length=10, choices=alerte_etat.ETATS, default=alerte_etat.A_VERIFIER, verbose_name=u"Etat")

    class Meta:
        ordering = ['date_alerte']

    def __str__(self):
        return self.date_alerte.strftime('%d-%m-%Y') + " " + self.etat


def find_by_id(id):
    return Alerte.objects.get(pk=id)


def find_by_etat(etat_alerte):
    return Alerte.objects.filter(etat=etat_alerte)


def find_by_etat_today(etat_alerte):
    date_d = timezone.now() - relativedelta(months=1)
    date_f = timezone.now() + relativedelta(months=1)
    return Alerte.objects.filter(etat=etat_alerte, date_alerte__lte=date_f, date_alerte__gte=date_d)


def find_all():
    return Alerte.objects.all().order_by('date_alerte')

main/models/assurance.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.db import models


class Assurance(models.Model):
    nom = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nom

    class Meta:
        ordering = ['nom']


def find_all():
    return Assurance.objects.all().order_by('nom')


def creation_assurance(un_nom):
    assurance = Assurance(nom=un_nom)
    return assurance.save()


def find_by_id(id):
    try:
        return Assurance.objects.get(pk=id)
    except Assurance.DoesNotExist:
        return None

main/models/honoraire.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.db import models
from django.contrib import admin
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from main.models import contrat_gestion as ContratGestion
from main.models.enums import etat_honoraire

MOIS_DE_BATTEMENT = 1


class HonoraireAdmin(admin.ModelAdmin):
    list_filter = ('etat',)


class Honoraire(models.Model):

    contrat_gestion = models.ForeignKey('ContratGestion', blank=True, null=True, verbose_name=u"Contrat de gestion")
    date_paiement = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True,
                                     verbose_name=u"Date paiement")
    etat = models.CharField(max_length=10, choices=etat_honoraire.ETAT_HONORAIRE, default=etat_honoraire.A_VERIFIER,
                            verbose_name=u"Etat")

    def __str__(self):
        if self.contrat_gestion:
            return str(self.contrat_gestion)
        else:
            return ""


def find_honoraires_by_etat_today(etat):
    if etat:
        return Honoraire.objects.filter(etat=etat,
                                        date_paiement__lte=timezone.now() + relativedelta(months=MOIS_DE_BATTEMENT),
                                        date_paiement__gte=timezone.now() - relativedelta(months=MOIS_DE_BATTEMENT))
    return None


def find_all():
    return Honoraire.objects.all()


def find_by_batiment_etat_date(batiment_id, etat, date_limite_inf, date_limite_sup):
    if batiment_id is None and etat is None and date_limite_inf is None and date_limite_sup is None:
        return Honoraire.objects.all()

    queryset = Honoraire.objects

    if batiment_id:
        queryset = queryset.filter(contrat_gestion__batiment__id=int(batiment_id))

    if etat:
        queryset = queryset.filter(etat=etat)

    if date_limite_inf:
        queryset = queryset.filter(date_paiement__gte=date_limite_inf)

    if date_limite_sup:
        queryset = queryset.filter(date_paiement__lte=date_limite_sup)

    return queryset


def find_all_batiments():
    batiments = []
    for c in ContratGestion.find_all():
        if c.batiment not in batiments:
            batiments.append(c.batiment)
    return batiments

main/templates/suivi/suivi_form.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block breadcrumb %}
    {%  if previous == 'liste' %}
      <li><a href="{% url 'suivis' %}">Les suivis</a></li>
      <li class="active">Suivi</li>
    {% endif %}
    {%  if previous == 'location' %}
        <li class="active">Location</li>
    {% endif %}
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'update_suivi' %}">
        {% csrf_token %}
        <input type="hidden" id="previous" name="previous" value="{{ previous }}"/>
        <input type="hidden" value="{{ date_debut|date:"j/m/Y"}}" name="date_debut"/>
        <input type="hidden" value="{{ date_fin|date:"j/m/Y"}}" name="date_fin"/>
        <input type="hidden" value="{{ etat }}" name="etat"/>
        <input type="hidden" value="{{ suivi.id }}" name="id"/>
        {% bootstrap_form form %}
        {% bootstrap_form_errors form %}
        <br>
        <button type="submit" class="btn btn-primary pull-right" title="Enregistrer les infos sur le suivi">
            <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"> Enregistrer</span>
        </button>
    </form>
{% endblock %}

{% block script %}
    <script>
        $("#txt_loyer_percu").blur(function(event) {
            var score = $(this).val().replace(',', '.');
            var regex = /^\d+(\.\d{0,2})?$/;
            $(this).val(score);
            score = $(this).val()
            if(!regex.test(score)){
                $(this).val('');
            }
        });
        $("#id_date_paiement_reel").datepicker({
            autoclose: true,
            orientation: "bottom auto",
            language: "fr",
            showOtherMonths: false
        });
        $("#id_date_paiement").datepicker({
            autoclose: true,
            orientation: "bottom auto",
            language: "fr",
            showOtherMonths: false
        });
        $("#id_date_paiement_reel").dblclick(function(event) {
            $("#id_date_paiement_reel" ).datepicker({dateFormat:"dd/mm/yy"}).datepicker("setDate",new Date());
        });

    </script>
{% endblock %}

main/templates/suivi/suivi_form_old.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block breadcrumb %}
    {%  if previous == 'liste' %}
      <li><a href="{% url 'suivis' %}">Les suivis</a></li>
      <li class="active">Suivi</li>
    {% endif %}
    {%  if previous == 'location' %}
        <li class="active">Location</li>
    {% endif %}
{% endblock %}

{% block content %}

    <form  method="post" action="{% url 'update_suivi' %}">
      {% csrf_token %}
      <input type="hidden" id="previous" name="previous" value="{{ previous }}"/>
      <input type="hidden" value="{{date_debut|date:"j/m/Y"}}" name="date_debut"/>
      <input type="hidden" value="{{date_fin|date:"j/m/Y"}}" name="date_fin"/>
      <input type="hidden" value="{{etat}}" name="etat"/>
      <input type="hidden" value="{{suivi.id}}" name="id"/>

      <div class="row">
        <div class="col-md-2">
          <label>Date paiement</label>
          <input class="form-control"
                 name="date_paiement"
                 title="Date théorique du paiement"
                 value="{{ suivi.date_paiement|date:"j/m/Y" }}" readonly>
        </div>
        <div class="col-md-2">
          <label>Date réelle paiement</label>
          <input class="form-control"
                 name="date_paiement_reel"
                 id="date_paiement_reel"
                 title="Date réelle du paiement"
                 value="{{ suivi.date_paiement_reel|date:"j/m/Y" }}">
        <span style="font-size: smaller;color:grey;">(Double clic = date du jour)</span>
          {% if form.date_paiement_reel.errors%}<span class="erreur_formulaire">{{form.date_paiement_reel.errors}}</span>{%endif%}
        </div>
      </div>
        <br>
      <div class="row">
        <div class="col-md-4">
          <label for="etat_suivi">Etat suivi</label>
          <select class="form-control"  name="etat_suivi" id="etat_suivi" >
            {% if suivi.etat_suivi == 'A_VERIFIER' %}
            <option value="A_VERIFIER" selected>A vérifier</option>
            {% else %}
            <option value="A_VERIFIER">A vérifier</option>
            {% endif %}
            {% if suivi.etat_suivi == 'IMPAYE' %}
            <option value="IMPAYE" selected>Impayé</option>
            {% else %}
            <option value="IMPAYE">Impayé</option>
            {% endif %}
            {% if suivi.etat_suivi == 'EN_RETARD' %}
            <option value="EN_RETARD" selected>En retard</option>
            {% else %}
            <option value="EN_RETARD">En retard</option>
            {% endif %}
            {% if suivi.etat_suivi == 'PAYE' %}
            <option value="PAYE" selected>Payé</option>
            {% else %}
            <option value="PAYE">Payé</option>
            {% endif %}
              {% if suivi.etat_suivi == 'SURPAYE' %}
                  <option value="SURPAYE" selected>Payé</option>
              {% else %}
                  <option value="SURPAYE">Sur-payé</option>
              {% endif %}

            {% if suivi.etat_suivi == 'TOUS' %}
            <option value="TOUS" selected>-</option>
            {% else %}
            <option value="TOUS">-</option>
            {% endif %}
          </select>
        </div>
        <div class="col-md-2">
        </div>

      </div>
    <br>
      <div class="row">
        <div class="col-md-4">
          <label>Loyer percu</label>
          <input type="text" class="form-control"
                 id="txt_loyer_percu"
                 value="{{suivi.loyer_percu}}" name="loyer_percu"> (
            <span >Loyer attendu :
                <span id="spn_loyer_percu">{{suivi.financement_location.loyer}}</span>
            </span>)
            <br>
            <span style="font-size: smaller;color:grey;">(Double clic => loyer percu = montant attendu et etat = 'payé'"</span>
            <input type="hidden" value="{{suivi.financement_location.loyer}}" id="hdn_loyer_attendu">
        </div>
        <div class="col-md-6">
          {% if suivi.financement_location.charges > 0 %}
          <label>Charges percues</label>
          <input type="number"  class="form-control" value="{{suivi.charges_percu}}" name="charges_percu">({{suivi.financement_location.charges}})
          {% endif %}
        </div>
      </div>
    <br>
      <div class="row">
        <div class="col-md-12">
          <label>Remarque</label>
          <input class="form-control" value="{{suivi.remarque| default_if_none:''}}" name="remarque">
        </div>
      </div>
      {% if form.errors%}<span class="erreur_formulaire">{{form.errors}}</span>{%endif%}
      <br>

        <button type="submit" class="btn btn-primary pull-right" title="Enregistrer les infos sur le suivi">
            <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"> Enregistrer</span>
        </button>


    </form>

{% endblock %}

{% block script %}
    <script>
        $("#txt_loyer_percu").blur(function(event) {
            var score = $(this).val().replace(',', '.');
            var regex = /^\d+(\.\d{0,2})?$/;
            $(this).val(score);
            score = $(this).val()
            if(!regex.test(score)){
                $(this).val('');
            }
        });

    </script>
{% endblock %}

main/templates/suivi/suivi_update.html
{% extends "layout.html" %}


{% block breadcrumb %}
  <li class="active">Sélection de suivi de loyer</li>
{% endblock %}

{% block content %}
<form method="get" action="{% url 'suivis_search'%}" >
  <div class="row">
    <div class="col-md-3">
    <label for="date_debut">Date début</label>
    <input class="form-control" id="date_debut" placeholder="Date début" value="{{ date_debut|date:"j/m/Y" }}" name="date_debut">
  </div>
  <div class="col-md-3">
    <label for="date_fin">Date fin</label>
    <input class="form-control" id="date_fin" placeholder="Date fin" value="{{ date_fin|date:"j/m/Y" }}" name="date_fin">
  </div>
  <div class="col-md-3">
    <label for="etat">Etat</label>
    <select class="form-control"  name="etat">
      <option value="A_VERIFIER" checked>A vérifier</option>
      <option value="IMPAYE">Impayé</option>
      <option value="EN_RETARD">En retard</option>
      <option value="PAYE">Payé</option>
      <option value="SURPAYE">Sur-payé</option>
      <option value="-">Tous</option>
    </select>
  </div>
  <div class="col-md-3">
    <label class="invisible">&nbsp;</label>
  <input type="submit" class="btn" value="Ok"/>
</div>
  </div>
</form>

{% if suivis|length > 0 %}
<form class="form-inline" method="POST" action="{% url 'suivis-update' %}">
  <table class="table table-condensed">
    <thead>
      <th>Batiment</th>
      <th>Date paiement</th>
      <th>Etat</th>
      <th>Loyer</th>
      <th>Charges</th>
      <th>Remarque</th>
    </thead>
    <tbody>
    {% for s in suivis %}
      <tr>
        <td>{{s.financement_location.contrat_location.batiment}}</td>
        <td><input type="" value="{{s.date_paiement|date:"j/m/Y"}}" id="suivi_date_paiement_{{ s.id }}" /></td>
        <td><input type="text" value="{{s.etat_suivi}}" id="suivi_etat_{{ s.id }}"/></td>
        <td><input type="number" value="{{s.loyer_percu}}" id="suivi_loyer_percu_{{ s.id }}"/>({{s.financement_location.loyer}})</td>

        <td><input type="number" value="{{s.charges_percu}}" id="suivi_charges_percu_{{ s.id }}"/>({{s.financement_location.charges}})</td>
        <td><input type="text" value="{{s.remarque| default_if_none:"-" }}" id="suivi_remarque_{{ s.id }}"/></td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
  <submit class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Enregistrer</submit>
  <a class="btn btn-default" role="button"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Annuler</a>
</form>
{%endif%}
{% endblock %}