app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main import assurance
urlpatterns = [
    url(r'', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^assurance_create/$', assurance.create, name='assurance_create'),
]

main/urls.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from . import views, batiment, proprietaire, suivis, contratlocation, financement, locataire, contratgestion, \
    frais, honoraire, personne, essai_pdf, assurance, pays, fonction, societe, document,\
    lettre
from main import alertes
from main.pdf import image
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.conf import settings


urlpatterns = [
    url(r'^$', views.home, name='home'),
    # login / logout urls
    url(r'^login/$', login, {'template_name': settings.LOGOUT_REDIRECT_URL}, name='login'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    # listes
    url(r'^listeComplete', views.listeComplete),
    url(r'^listeBatiments', views.listeBatiments, name='listeBatiments'),

    url(r'^listeProprietaires', proprietaire.liste_proprietaires, name='listeProprietaires'),
    url(r'^listeContratGestion/$', views.ContratGestionList.as_view(), name='contrat_gestion_list'),
    url(r'^contratGestion/(?P<pk>[0-9]+)/$', views.ContratGestionDetail.as_view(), name='contrat_gestion_detail'),
    # ecran de detail
    url(r'^batiment/([0-9]+)/$', batiment.batiment_form, name='batiment'),
    url(r'^proprietaire/(?P<proprietaire_id>[0-9]+)/$', proprietaire.proprietaire, name='proprietaire'),
    url(r'^proprietaire/update/([0-9]+)/$', proprietaire.update_proprietaire, name='update_proprietaire'),
    url(r'^proprietaire/delete/([0-9]+)/$', proprietaire.delete_proprietaire, name='delete_proprietaire'),
    url(r'^proprietaire/dadd/([0-9]+)/$', proprietaire.add_proprietaire, name='add_proprietaire'),
    url(r'^proprietaire/$', proprietaire.proprietaire_update_save, name='proprietaire-update-save'),
    url(r'^proprietaire/createb/([0-9]+)/$', proprietaire.proprietaire_create_for_batiment,
        name='proprietaire-create-batiment'),

    # old
    # url(r'^suivis/$', suivis.suivis, name='suivis'),
    # url(r'^suivis/refresh/$', suivis.refresh_suivis, name='refresh_suivis'),
    url(r'^suivis/$', suivis.suivis, name='suivis'),
    url(r'^suivis/search$', suivis.suivis_search, name='suivis_search'),
    url(r'^suivis/update$', suivis.suivis_update, name='suivis-update'),
    # url(r'^suivis/updatel/([0-9]+)/$', suivis.suivis_updatel, name='suivis-updatel'),
    url(r'^suivis/updatel/([0-9]+)/liste/$', suivis.suivis_update_liste, name='suivis-update-liste'),
    url(r'^suivis/updatel/([0-9]+)/home/$', suivis.suivis_update_home, name='suivis-update-home'),
    url(r'^suivis/updatel/([0-9]+)/location/$', suivis.suivis_update_location, name='suivis-update-location'),

    url(r'^suivis/update_suivi$', suivis.update_suivi, name='update_suivi'),


    # url(r'^update_personne/$', views.update_personne, name='update_personne'),
    url(r'^update_batiment(?:/(?P<batiment_id>[0-9]+))?/$', batiment.update, name='update_batiment'),


    # url(r'^photos/(?P<path>.*)$', 'django.views.static.serve', {
    #         'document_root': settings.MEDIA_ROOT,
    #     }),

    url(r'^fraismaintenances/$', frais.list, name='fraismaintenance_list'),
    url(r'^fraismaintenance/new/$', frais.new, name='fraismaintenance-new'),
    url(r'^fraismaintenance/create/([0-9]+)/$', frais.create, name='fraismaintenance-create'),
    url(r'^fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update, name='fraismaintenance-prepare-update'),
    url(r'^fraismaintenance/update/$', frais.update, name='fraismaintenance-update'),
    url(r'^fraismaintenance/delete/([0-9]+)/$', frais.delete_frais, name='fraismaintenance-delete'),
    url(r'^fraismaintenance/(?P<pk>[0-9]+)/$', views.FraisMaintenanceDetail.as_view(), name='fraismaintenance_detail'),

    url(r'^personne/create/$', personne.create, name='personne-create'),
    url(r'^personne/create/locataire/$', locataire.personne_create, name='personne-create-locataire'),
    url(r'^personne/create2019/$', personne.personne_create_2019, name='personne-create-2019'),
    url(r'^personne/create/proprietaire/$', proprietaire.personne_create, name='personne-create-proprietaire'),

    url(r'^personne/edit/([0-9]+)/$', personne.edit, name='personne-edit'),
    url(r'^personne/update/$', personne.update, name='personne-update'),
    url(r'^personne/delete/(?P<pk>[0-9]+)/$', views.PersonneDelete.as_view(), name='personne-delete'),
    url(r'^personne/delete2/([0-9]+)/$', views.personne_delete, name='personne-delete-2'),
    url(r'^personnes/$', personne.list, name='personne_list'),
    url(r'^personnes/search/$', personne.search, name='personne_search'),
    url(r'^validate_personne/$', personne.validate_personne, name='validate_personne'),

    url(r'^batiment/create/$', batiment.create, name='batiment-create'),
    url(r'^batiment/([0-9]+)/$', batiment.batiment_form, name='batiment'),
    url(r'^batiment/update/([0-9]+)/$', batiment.update, name='batiment-update'),
    url(r'^batiment/delete/([0-9]+)/$', batiment.delete, name='batiment-delete'),
    url(r'^batiments/$', views.BatimentList.as_view(), name='batiment_list'),
    url(r'^batiment/deletep/([0-9]+)/$', proprietaire.delete_proprietaire_batiment,
        name='delete_proprietaire_batiment'),
    url(r'^batiment/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_batiment,
        name='fraismaintenance-edit-from-batiment'),
    url(r'^location/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_location,
        name='fraismaintenance-edit-from-location'),
    url(r'^dashboard/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_dashboard,
        name='fraismaintenance-edit-from-dashboard'),
    url(r'^frais/list/fraismaintenance/prepare/update/([0-9]+)/$', frais.prepare_update_from_list,
        name='fraismaintenance-edit-from-list'),

    url(r'^batiment/fraismaintenance/delete/([0-9]+)/$', frais.delete_frais_from_batiment,
        name='fraismaintenance-delete-from-batiment'),
    url(r'^location/fraismaintenance/delete/([0-9]+)/$', frais.delete_frais_from_location,
        name='fraismaintenance-delete-from-location'),
    url(r'^frais/liste/fraismaintenance/delete/([0-9]+)/$', frais.delete_frais_from_list,
        name='fraismaintenance-delete-from-list'),
    # url(r'^proprietaire/create/$', views.ProprietaireCreate.as_view(), name='proprietaire-create'),
    # url(r'^proprietaire/createb/(?P<pk>[0-9]+)/$', views.ProprietaireCreateForBatiment.as_view(),
    # name='proprietaire-create-batiment'),
    # url(r'^proprietaire/update/(?P<pk>[0-9]+)/$', views.ProprietaireUpdate.as_view(), name='proprietaire-update'),
    # url(r'^proprietaire/delete/(?P<pk>[0-9]+)/$', views.ProprietaireDelete.as_view(), name='proprietaire-delete'),
    # url(r'^proprietaires/$', views.ProprietaireList.as_view(), name='proprietaire_list'),
    # url(r'^proprietaire/(?P<pk>[0-9]+)/$', views.ProprietaireDetail.as_view(), name='proprietaire_detail'),
    url(r'^contratgestion/new/$', contratgestion.new, name='contratgestion-new'),
    url(r'^contratgestion/create/([0-9]+)/$', contratgestion.create, name='contratgestion-create'),
    # url(r'^contratgestion/update/(?P<pk>[0-9]+)/$', views.ContratGestionUpdate.as_view(),
    # name='contratgestion-update'),
    url(r'^contratgestion/delete/([0-9]+)/$', contratgestion.delete, name='contratgestion-delete'),
    url(r'^gestion/prepare/update/all/([0-9]+)/$', contratgestion.prepare_update, name='gestion-prepare-update-all'),
    url(r'^gestion/update/all/$', contratgestion.update, name='update-gestion-all'),
    url(r'^contratgestion/form/(?P<id_contrat>[0-9]+)/$', contratgestion.saveupdate, name='gestion-create-update'),



    url(r'^contratgestions/$', contratgestion.list, name='contratgestion_list'),

    # url(r'^contratgestion/(?P<pk>[0-9]+)/$', views.ContratGestionDetail.as_view(), name='contratgestion'),

    url(r'^societe/delete/(?P<pk>[0-9]+)/$', views.SocieteDelete.as_view(), name='societe-delete'),
    url(r'^societes/$', societe.list, name='societe-list'),
    url(r'^societe/(?P<pk>[0-9]+)/$', views.SocieteDetail.as_view(), name='societe'),
    url(r'^societe/create/personne/$', societe.create, name='personne-create-societe'),
    # url(r'^batiment5/(?P<pk>\d+)/$', BatimentDetailView.as_view(), batiment_info)
    url(r'^alertes/$', alertes.list, name='alerte-list'),
    url(r'^alertes/update/$', alertes.update_a_verifier, name='alerte-update-a-verifier'),
    url(r'^alertes/search/$', alertes.search, name='alerte-search'),

    # url(r'^location/create/$', views.ContratLocationCreate.as_view(), name='location-create'),
    # url(r'^location/update/(?P<pk>[0-9]+)/$', views.ContratLocationUpdate.as_view(), name='location-update'),

    url(r'^location/prepare/update/all/([0-9]+)/$', contratlocation.prepare_update, name='location-prepare-update-all'),
    url(r'^location/update/all/$', contratlocation.update, name='update-location-all'),
    url(r'^location/createb/([0-9]+)/$', contratlocation.contrat_location_for_batiment,

main/models/alerte.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.db import models
from django.contrib import admin
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from main.models.enums import alerte_etat


class AlerteAdmin(admin.ModelAdmin):
    list_filter = ('etat',)


class Alerte(models.Model):

    description = models.TextField(verbose_name=u"Description")
    date_alerte = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True,
                                   verbose_name=u"Date alerte")
    contrat_gestion = models.ForeignKey('ContratGestion', blank=True, null=True, verbose_name=u"Contrat de gestion")
    contrat_location = models.ForeignKey('ContratLocation', blank=True, null=True, verbose_name=u"Contrat location")
    etat = models.CharField(max_length=10, choices=alerte_etat.ETATS, default=alerte_etat.A_VERIFIER, verbose_name=u"Etat")

    class Meta:
        ordering = ['date_alerte']

    def __str__(self):
        return self.date_alerte.strftime('%d-%m-%Y') + " " + self.etat


def find_by_id(id):
    return Alerte.objects.get(pk=id)


def find_by_etat(etat_alerte):
    return Alerte.objects.filter(etat=etat_alerte)


def find_by_etat_today(etat_alerte):
    date_d = timezone.now() - relativedelta(months=1)
    date_f = timezone.now() + relativedelta(months=1)
    return Alerte.objects.filter(etat=etat_alerte, date_alerte__lte=date_f, date_alerte__gte=date_d)


def find_all():
    return Alerte.objects.all().order_by('date_alerte')

main/models/assurance.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.db import models


class Assurance(models.Model):
    nom = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nom

    class Meta:
        ordering = ['nom']


def find_all():
    return Assurance.objects.all().order_by('nom')


def creation_assurance(un_nom):
    assurance = Assurance(nom=un_nom)
    return assurance.save()


def find_by_id(id):
    try:
        return Assurance.objects.get(pk=id)
    except Assurance.DoesNotExist:
        return None

main/models/banque.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.db import models


class Banque(models.Model):
    nom = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nom


def get_pays_choix():
    return ['Belgique']

main/models/document_modele.py
##############################################################################
#
#    Immobilier it's an application
#    designed to manage the core business of property management, buildings,
#    rental agreement and so on.
#
#    Copyright (C) 2016-2018 Verpoorten Leïla
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.l
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.db import models
from ckeditor.fields import RichTextField


class DocumentModele(models.Model):
    # TYPE_DOCUMENT = (
    # ('LETTRE_INDEXATION', 'Lettre indexation'),
    # )
    reference = models.CharField(max_length=50, blank=True, null=True)
    contenu = RichTextField()
    sujet = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.reference


def find_by_reference(a_reference):
    return DocumentModele.objects.get(reference=a_reference)


def find_all():
    return DocumentModele.objects.all()


def find_by_id(a_document_id):
    return DocumentModele.objects.get(pk=a_document_id)

main/templates/honoraire/honoraire_form.html
{% extends "layout.html" %}
{% block breadcrumb %}
<li><a href="{% url 'honoraire-list' %}">Liste honoraires</a></li>
<li class="active">Honoraire</li>
{% endblock %}
{% block content %}

<form method="post" action="{% url 'honoraire-update' %}">
    {% csrf_token %}
    <input type="hidden" id="previous" name="previous" value="{{request.META.HTTP_REFERER }}"/>
    <input type="hidden" value="{{ honoraire.id }}" name="honoraire_id"/>
    <input type="hidden" name="next"
           value="{{next}}" />
    <br>
    <div class="row">
        <div class="col-md-12">
            <label>Contrat</label>
            {% if honoraire.contrat_gestion %}
                <br>
                {{ honoraire.contrat_gestion | default_if_none:'' }}
            {%endif%}
            {% if honoraire.contrat_location %}
                <input class="form-control"
                       value="{{ honoraire.contrat_location | default_if_none:'' }}" readonly>
            {%endif%}
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-2">
            <label>Date paiement attendu</label>
            <input class="form-control"
                   name="date_paiement"
                   value="{{ honoraire.date_paiement|date:" j/m/Y"| default_if_none:'' }}" readonly>
        </div>
        <div class="col-md-4">
            <label for="etat">Etat</label>
            <select class="form-control" name="etat" id="etat">
                {% if honoraire.etat == 'A_VERIFIER' %}
                <option value="A_VERIFIER" selected>A vérifier</option>
                {% else %}
                <option value="A_VERIFIER">A vérifier</option>
                {% endif %}
                {% if honoraire.etat == 'IMPAYE' %}
                <option value="IMPAYE" selected>Impayé</option>
                {% else %}
                <option value="IMPAYE">Impayé</option>
                {% endif %}
                {% if honoraire.etat == 'EN_RETARD' %}
                <option value="EN_RETARD" selected>En retard</option>
                {% else %}
                <option value="EN_RETARD">En retard</option>
                {% endif %}
                {% if honoraire.etat == 'PAYE' %}
                <option value="PAYE" selected>Payé</option>
                {% else %}
                <option value="PAYE">Payé</option>
                {% endif %}
            </select>
        </div>
    </div>

    <br>

    <div class="pull-right">
        <button type="submit" class="btn btn-primary" title="Sauvegarder">
            <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"> Enregistrer</span>
        </button>
        &nbsp;
    </div>

</form>
{% endblock %}

main/templates/honoraire/honoraire_list.html
{% extends "layout.html" %}
{% load staticfiles %}

{% cycle 'row1' 'row2' as rowcolors %}
{% block breadcrumb %}
  <li class="active">Liste des honoraires</li>
{% endblock %}
{% block content %}
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
        <div class="col-md-12">
            <div class="panel  panel-info">
                <div class="panel-heading">Filtrer par</div>
                <div class="panel-body">
                    <form method="get" action="{% url 'honoraires-search'%}">
                        <div class="row">
                            <div class="col-md-3">
                                <label>Local</label>
                                <select class="form-control" name="batiment_id" >
                                    {%if batiment %}
                                        <option value="TOUS" >Tous</option>
                                    {%else%}
                                        <option value="TOUS" selected>Tous</option>
                                    {%endif%}
                                    {% for b in batiments %}
                                        {% if batiment == b.id %}
                                            <option value="{{ b.id }}" selected>{{ b }}{{batiment}}</option>
                                        {%else%}
                                            <option value="{{ b.id }}">{{ b }}{{batiment}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label for="etat">Etat</label>
                                <select class="form-control"  name="etat" id ="etat">
                                    {% if etat == 'A_VERIFIER' %}
                                        <option value="A_VERIFIER" selected>A vérifier</option>
                                    {% else %}
                                        <option value="A_VERIFIER">A vérifier</option>
                                    {% endif %}
                                    {% if etat == 'IMPAYE' %}
                                        <option value="IMPAYE" selected>Impayé</option>
                                    {% else %}
                                        <option value="IMPAYE">Impayé</option>
                                    {% endif %}
                                    {% if etat == 'EN_RETARD' %}
                                        <option value="EN_RETARD" selected>En retard</option>
                                    {% else %}
                                        <option value="EN_RETARD">En retard</option>
                                    {% endif %}
                                    {% if etat == 'PAYE' %}
                                        <option value="PAYE" selected>Payé</option>
                                    {% else %}
                                        <option value="PAYE">Payé</option>
                                    {% endif %}
                                    {% if etat == 'TOUS' %}
                                        <option value="TOUS" selected>Tous</option>
                                    {% else %}
                                        <option value="TOUS">Tous</option>
                                    {% endif %}
                                </select>
                            </div>
                            <div class="col-md-2">
                                <label >Date inférieure</label>
                                <input class="form-control"
                                       id="txt_date_limite"
                                       value="{% if date_limite %}{{ date_limite|date:"j/m/Y" }}{%endif%}" name="date_limite"/>
                                <span class="erreur_formulaire" id="spn_date_limite"></span>
                            </div>
                            <div class="col-md-2">
                                <label >Date supérieure</label>
                                <input class="form-control"
                                       id="txt_date_limite_sup"
                                       value="{% if date_limite_sup %}{{ date_limite_sup|date:"j/m/Y" }}{%endif%}" name="date_limite_sup"/>
                                <span class="erreur_formulaire" id="spn_date_limite_sup"></span>
                            </div>
                            <div class="col-md-2">
                                <button type="submit" id="bt_honoraire_search"  class="btn btn-default pull-right" >
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div ></div>
        {% include "honoraire/sub_honoraire_list.html" %}
    </div>
</div>
</div>

{% endblock %}

main/templates/honoraire/sub_honoraire_list.html
    <table class="table table-hover" id="tbl_data_honoraires">
        <thead>
            <tr>
                <th></th>
                <th>Contrat</th>
                <th class="no-sort">Montant mensuel</th>
                <th>Date paiement attendu</th>
                <th>Etat</th>
                <th class="no-sort"></th>
            </tr>
        </thead>
    <tbody>
        {% for honoraire in honoraires %}
            <tr>
                <td style="visibility:hidden;">{{honoraire.contrat_gestion.id}}</td>
                <td>
                    <a href="{% url 'gestion-prepare-update-all' honoraire.contrat_gestion.pk%}"
                       title="Pour modifier un contrat de gestion">
                        {{ honoraire.contrat_gestion.batiment }}
                    </a>
                </td>
                <td>{{ honoraire.contrat_gestion.montant_mensuel| default_if_none:'' }}</td>
                <td>
                    {% if honoraire.date_paiement %}
                        {{ honoraire.date_paiement|date:"j/m/Y"  }}
                    {% endif%}</td>
                <td style="background-color:
                        {%if honoraire.etat == 'PAYE' %}
                            transparent
                        {% else %}
                            {%if honoraire.etat == 'IMPAYE' %}
                                red
                            {% else %}
                                orange
                            {% endif %}
                        {% endif %};">
                    {{ honoraire.get_etat_display }}
                </td>
                <td>
                    <a href="{% url 'honoraire' honoraire.id%}" title="Pour modifier un honoraire">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>
                    <a href="{% url 'honoraire-delete' honoraire.pk%}" title="Pour supprimer un honoraire" style="visibility:hidden;display:none;">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </a>
                </td>
            </tr>
        {% endfor%}
    </tbody>
    </table>